### PR TITLE
Update build.gradle for external variables

### PR DESCRIPTION
**Pull request by gevorg-kopalyan**
Proper way to check externally set variables otherwise it won't be posible to set them

### CODE REVIEW

**Comment by gevorg-kopalyan** [comment]
I signed it!

**Comment by samtstern** [comment]
LGTM, merging

**Comment by samtstern** [comment]
Hmmm did you sign the CLA with the same email address that is associated with this github account?  If not, what email address did you sign with?

**Comment by gevorg-kopalyan** [comment]
Yeap I sign it with gevorg.kopalyan@gmail.com and github account gevorg-kopalyan

**Comment by azakhary** [comment]
+1 to this.

**Comment by samtstern** [comment]
@gevorg-kopalyan I know it's annoying but I am still not seeing the signature on my end.  Can you maybe just attach a screenshot of proof here so I can merge this change?  It's possible my view of the data is broken.

**Comment by gevorg-kopalyan** [comment]
Sure no problem
scr

**Comment by samtstern** [comment]
LGTM, thank you/

**Pull request merged**
